import { ProductModule, ProductService } from "./types"

export const MOCK_PRODUCTS: ProductModule[] = [
  { id: "P-2001", product_code: "PHM-CORE",   product_name: "Pharmacy Suite",        description: "Full pharmacy inventory, billing and prescription management.", category: "Pharmacy",    type: "core",   price: 24999, tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-01", updated_at: "2026-05-12", created_by: "Hari" },
  { id: "P-2002", product_code: "CLN-CORE",   product_name: "Clinic Suite",          description: "Patient records, appointments and consultation workflows.",     category: "Clinic",      type: "core",   price: 29999, tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-01", updated_at: "2026-05-10", created_by: "Hari" },
  { id: "P-2003", product_code: "INV-ADDON",  product_name: "Inventory Manager",     description: "Stock tracking with low-stock alerts and batch expiry.",        category: "Pharmacy",    type: "add_on", price: 7999,  tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-05", updated_at: "2026-04-22", created_by: "Sujjeeth" },
  { id: "P-2004", product_code: "BIL-ADDON",  product_name: "Billing Module",        description: "GST-compliant invoicing and payment reconciliation.",           category: "Finance",     type: "add_on", price: 5999,  tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-08", updated_at: "2026-04-18", created_by: "Sujjeeth" },
  { id: "P-2005", product_code: "LAB-ADDON",  product_name: "Lab Integration",       description: "Connects lab equipment and report delivery to patients.",       category: "Clinic",      type: "add_on", price: 8999,  tax_percentage: 18, status: "inactive", notes: "Pending vendor certification", created_at: "2026-02-20", updated_at: "2026-04-01", created_by: "Hari" },
  { id: "P-2006", product_code: "APT-ADDON",  product_name: "Appointment Scheduler", description: "Calendar sync, reminders and waitlist management.",             category: "Clinic",      type: "add_on", price: 4999,  tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-15", updated_at: "2026-05-02", created_by: "Sujjeeth" },
  { id: "P-2007", product_code: "SMS-ADDON",  product_name: "SMS Notifications",     description: "Automated SMS for appointments, refills and offers.",           category: "Engagement",  type: "add_on", price: 1999,  tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-20", updated_at: "2026-04-29", created_by: "Hari" },
  { id: "P-2008", product_code: "REC-CORE",   product_name: "Patient Records",       description: "Centralised EMR with history, allergies and prescriptions.",     category: "Clinic",      type: "core",   price: 19999, tax_percentage: 18, status: "inactive", notes: "Replaced by Clinic Suite v2", created_at: "2026-01-10", updated_at: "2026-03-30", created_by: "Hari" },
]

export const MOCK_SERVICES: ProductService[] = [
  { id: "S-3001", service_code: "ONB-001", service_name: "Onboarding & Setup",      description: "Initial configuration, data import and team training.",         category: "Implementation", type: "core",   duration: "3 days",   price: 9999,  tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-01", updated_at: "2026-05-12", created_by: "Hari" },
  { id: "S-3002", service_code: "MIG-002", service_name: "Data Migration",          description: "Migrate legacy records from spreadsheets or older systems.",     category: "Implementation", type: "add_on", duration: "5 days",   price: 14999, tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-04", updated_at: "2026-04-20", created_by: "Sujjeeth" },
  { id: "S-3003", service_code: "TRN-003", service_name: "Custom Training",         description: "On-site or remote training sessions for staff.",                category: "Support",        type: "add_on", duration: "1 day",    price: 4999,  tax_percentage: 18, status: "active",   notes: "", created_at: "2026-03-10", updated_at: "2026-04-15", created_by: "Hari" },
  { id: "S-3004", service_code: "SUP-004", service_name: "Priority Support",        description: "24x7 priority ticket handling with 1 hour SLA.",                 category: "Support",        type: "core",   duration: "Ongoing",  price: 2999,  tax_percentage: 18, status: "active",   notes: "Billed monthly", created_at: "2026-02-15", updated_at: "2026-05-01", created_by: "Sujjeeth" },
  { id: "S-3005", service_code: "API-005", service_name: "API Integration Service", description: "Connect third-party labs, payment gateways or ERPs.",            category: "Integration",    type: "add_on", duration: "2 weeks",  price: 19999, tax_percentage: 18, status: "inactive", notes: "Needs scoping call first", created_at: "2026-02-01", updated_at: "2026-03-22", created_by: "Hari" },
  { id: "S-3006", service_code: "AMC-006", service_name: "Annual Maintenance",      description: "Updates, backups and uptime monitoring for one year.",           category: "Support",        type: "core",   duration: "12 months", price: 12999, tax_percentage: 18, status: "active",   notes: "", created_at: "2026-01-20", updated_at: "2026-04-28", created_by: "Sujjeeth" },
]
